// 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨  
// DO NOT EDIT: Generated by model-codegen 
// 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 
const { 
  BaseModel, 
  UNIQUE_CONSTRAINT_ID1,
  PrimaryKeyConfig,
  UniqueConstraintConfig
} = require('dynamo-bao');

const { 
    UlidField,
    StringField,
    CreateDateField,
    ModifiedDateField
} = require('dynamo-bao').fields;



class User extends BaseModel {
  static modelPrefix = 'u';
  
  static fields = {
    userId: UlidField({ required: true, autoAssign: true }),
    name: StringField({ required: true }),
    email: StringField({ required: true }),
    profilePictureUrl: StringField(),
    createdAt: CreateDateField(),
    modifiedAt: ModifiedDateField(),
  };

  static primaryKey = PrimaryKeyConfig('userId', 'modelPrefix');


  static uniqueConstraints = {
    uniqueEmail: UniqueConstraintConfig('email', UNIQUE_CONSTRAINT_ID1),
  };


  static async cgFindByEmail(value) {
    return await this.findByUniqueConstraint('uniqueEmail', value);
  }

}

module.exports = { User };
