// 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨  
// DO NOT EDIT: Generated by model-codegen 
// 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 
const { 
  BaoModel,
  PrimaryKeyConfig,
  IndexConfig
} = require('dynamo-bao/src/model.js');

const {
  GSI_INDEX_ID1
} = require('dynamo-bao/src/constants.js');

const { 
    UlidField,
    RelatedField,
    StringField,
    DateTimeField,
    CreateDateField,
    TtlField
} = require('dynamo-bao/src/fields.js');




class AdminSession extends BaoModel {
  static modelPrefix = 'as';
  static iterable = false;
  static iterationBuckets = 100;
  
  static fields = {
    sessionId: UlidField({ autoAssign: true, required: true }),
    adminId: RelatedField('AdminUser', { required: true }),
    accessToken: StringField({ required: true }),
    refreshToken: StringField({ required: true }),
    expiresAt: DateTimeField({ required: true }),
    createdAt: CreateDateField(),
    lastActivity: DateTimeField(),
    ttl: TtlField(),
  };

  static primaryKey = PrimaryKeyConfig('sessionId', 'modelPrefix');

  static indexes = {
    sessionsForAdmin: IndexConfig('adminId', 'createdAt', GSI_INDEX_ID1),
  };




  async getAdmin() {
    return await this.getOrLoadRelatedField('adminId');
  }
}

module.exports = { AdminSession };
