// 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨  
// DO NOT EDIT: Generated by model-codegen 
// 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 🧨 
const { 
  BaoModel,
  PrimaryKeyConfig
} = require('dynamo-bao/src/model.js');


const { 
    RelatedField,
    StringField,
    CreateDateField
} = require('dynamo-bao/src/fields.js');




class InvitedUser extends BaoModel {
  static modelPrefix = 'inv';
  static iterable = true;
  static iterationBuckets = 10;
  
  static fields = {
    appId: RelatedField('App', { required: true }),
    email: StringField({ required: true }),
    invitedAt: CreateDateField(),
    invitedBy: StringField({ required: true }),
  };

  static primaryKey = PrimaryKeyConfig('appId', 'email');





  async getApp() {
    return await this.getOrLoadRelatedField('appId');
  }
}

module.exports = { InvitedUser };
