service: raftjs-dynamo

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-west-2'}
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: _pk
            AttributeType: S
          - AttributeName: _sk
            AttributeType: S
          - AttributeName: _gsi1_pk
            AttributeType: S
          - AttributeName: _gsi1_sk
            AttributeType: S
          - AttributeName: _gsi2_pk
            AttributeType: S
          - AttributeName: _gsi2_sk
            AttributeType: S
          - AttributeName: _gsi3_pk
            AttributeType: S
          - AttributeName: _gsi3_sk
            AttributeType: S
          - AttributeName: _gsi4_pk
            AttributeType: S
          - AttributeName: _gsi4_sk
            AttributeType: S
          - AttributeName: _gsi_test_id
            AttributeType: S
        KeySchema:
          - AttributeName: _pk
            KeyType: HASH
          - AttributeName: _sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
              - AttributeName: _gsi1_pk
                KeyType: HASH
              - AttributeName: _gsi1_sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi2
            KeySchema:
              - AttributeName: _gsi2_pk
                KeyType: HASH
              - AttributeName: _gsi2_sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi3
            KeySchema:
              - AttributeName: _gsi3_pk
                KeyType: HASH
              - AttributeName: _gsi3_sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi4
            KeySchema:
              - AttributeName: _gsi4_pk
                KeyType: HASH
              - AttributeName: _gsi4_sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi_test
            KeySchema:
              - AttributeName: _gsi_test_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: _ttl
          Enabled: true
          