// THIS FILE IS AUTO-GENERATED by dynamo-bao codegen.
// DO NOT EDIT DIRECTLY.
import * as model0 from '../models/comment.js';
import * as model1 from '../models/post.js';
import * as model2 from '../models/tag.js';
import * as model3 from '../models/tagged-post.js';
import * as model4 from '../models/user.js';

export default {
  ...model0,
  ...model1,
  ...model2,
  ...model3,
  ...model4
};
