// THIS FILE IS AUTO-GENERATED by dynamo-bao codegen.
// DO NOT EDIT DIRECTLY.
import * as model0 from '../generated/comment.js';
import * as model1 from '../generated/post.js';
import * as model2 from '../generated/user.js';

export default {
  ...model0,
  ...model1,
  ...model2
};
