// THIS FILE IS AUTO-GENERATED by dynamo-bao codegen.
// DO NOT EDIT DIRECTLY.
import * as model0 from '../models/admin-session.js';
import * as model1 from '../models/admin-user.js';
import * as model2 from '../models/app.js';
import * as model3 from '../models/connection-mapping.js';
import * as model4 from '../models/document-permission.js';
import * as model5 from '../models/document.js';
import * as model6 from '../models/invited-user.js';
import * as model7 from '../models/session.js';
import * as model8 from '../models/user.js';

export default {
  ...model0,
  ...model1,
  ...model2,
  ...model3,
  ...model4,
  ...model5,
  ...model6,
  ...model7,
  ...model8
};
