// THIS FILE IS AUTO-GENERATED by dynamo-bao codegen.
// DO NOT EDIT DIRECTLY.
import * as model0 from '../generated/comment.js';
import * as model1 from '../generated/post.js';
import * as model2 from '../generated/tag.js';
import * as model3 from '../generated/tagged-post.js';
import * as model4 from '../generated/user-profile.js';
import * as model5 from '../generated/user-with-email.js';
import * as model6 from '../generated/user.js';

export default {
  ...model0,
  ...model1,
  ...model2,
  ...model3,
  ...model4,
  ...model5,
  ...model6
};
